### ISSUE TITLE
Errors in error.log

### ISSUE THREAD

**Issue by akapucu** [SSHCure/SSHCure#63]
I just installed new version.

i am receiving this in error.log when i try to see page

Is it easy fix?

[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Warning:  socket_last_error() expects parameter 1 to be resource, integer given in /var/www/nfsen/nfsenutil.php on line 114, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Warning:  socket_last_error() expects parameter 1 to be resource, integer given in /var/www/nfsen/nfsenutil.php on line 115, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Warning:  socket_last_error() expects parameter 1 to be resource, integer given in /var/www/nfsen/nfsenutil.php on line 119, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Parse error:  syntax error, unexpected '[' in /var/www/nfsen/plugins/SSHCure/json/data/get_top_targets_compromise.php on line 32, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:01 2015] [error] [client 131.x.x.x] PHP Parse error:  syntax error, unexpected '[' in /var/www/nfsen/plugins/SSHCure/json/data/get_top_targets_bruteforce.php on line 33, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Mon Apr 27 15:54:05 2015] [error] [client 131.x.x.x] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=incoming
[Mon Apr 27 15:54:09 2015] [error] [client 131.x.x.x] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=outgoing

**Comment by rickhofstede** [comment]
Since your Web server is complaining about 'syntax errors' in two projects (NfSen, first three reports, and SSHCure, remaining reports), it's more likely that you have a compatibility issue. I'm curious to know what is causing it.

Could you please check what is the version of PHP running on your system? And does NfSen itself run fine (i.e., when you navigate to http://netflow.server.com/nfsen.nfsen.php on your system)?

**Comment by akapucu** [comment]
Hi Rick,


I dont have issue on nfsen


Nfsen is running good,

Surfmap is running good



here is error logs

[Fri May 01 09:30:03 2015] [error] [client 10.143.118.38] PHP Notice:  Undefined variable: chan_id in /var/www/nfsen/profileadmin.php on line 593, referer: http://netflow.server.com/nfsen/nfsen.php?tab=3
[Fri May 01 09:30:03 2015] [error] [client 10.143.118.38] PHP Notice:  Undefined variable: chan_id in /var/www/nfsen/profileadmin.php on line 594, referer: http://netflow.server.com/nfsen/nfsen.php?tab=3
[Fri May 01 09:30:39 2015] [error] [client 10.143.118.38] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Fri May 01 09:30:39 2015] [error] [client 10.143.118.38] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Fri May 01 09:30:39 2015] [error] [client 10.143.118.38] PHP Parse error:  syntax error, unexpected '[' in /var/www/nfsen/plugins/SSHCure/json/data/get_top_targets_compromise.php on line 32, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Fri May 01 09:30:39 2015] [error] [client 10.143.118.38] PHP Parse error:  syntax error, unexpected '[' in /var/www/nfsen/plugins/SSHCure/json/data/get_top_targets_bruteforce.php on line 33, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard
[Fri May 01 09:30:53 2015] [error] [client 10.143.118.38] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/nfsen/plugins/SSHCure/json/data/get_attacks.php on line 39, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=outgoing
^C
[root@netflow:/var/www/nfsen]#




First 2 logs when i try to go Surfmap rest of them belongs to SSHCure. It keep saying Loading on the web page


here is php version


[root@netflow:/var/www/nfsen]# php -v
PHP 5.3.10-1ubuntu3.18 with Suhosin-Patch (cli) (built: Apr 17 2015 15:04:29)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies



________________________________

**Comment by rickhofstede** [comment]
Thanks for your feedback. It turns out that we had some syntax constructs that were only supported as of PHP 5.4, while you appear to be running PHP 5.3. Please checkout the latest master.

**Comment by akapucu** [comment]
Thank you


That fixed it.


Looks like dashboard asking for get_internal_networks.php ?? but git has comment for rpc folder "Dashboard does not depend on json/rpc/get_internal_networks.php anymore<https://github.com/SSHCure/SSHCure/commit/78db3e0e2af35eaab0f22e5bf3f82b414eaf599f>"



[Fri May 01 10:00:32 2015] [error] [client 10.143.118.38] script '/var/www/nfsen/plugins/SSHCure/json/rpc/get_internal_networks.php' not found or unable to stat, referer: http://netflow.server.com/nfsen/plugins/SSHCure/index.php?action=dashboard


________________________________

**Comment by rickhofstede** [comment]
Assuming that you've properly 'reinstalled' the latest version of SSHCure, I suspect your browser cache to be the problem here. We've indeed removed `get_internal_networks.php` yesterday, as well as the accompanying call from `dashboard.js`. There's probably an old version of `dashboard.js` in your cache.

**Comment by akapucu** [comment]
You were right :)

--


Thanks

________________________________

**Comment by akapucu** [comment]
Rick,

FYI,


Looks like same array syntax  are using on


json/html/*

**Comment by rickhofstede** [comment]
Should be fixed now as well.
