### ISSUE TITLE
SSHCure direct commands

### ISSUE THREAD

**Issue by eljeffeg** [SSHCure/SSHCure#67]
I can't get NFSEN to work and I've been at it for hours.  I'm just trying to run SSHCure on my historical netflow data that I copied over to the system.  I've got the plugin installed but can't see my data in NFSEN unless I use a very specific time that matches one of the filenames.  

Is there any way to just run SSHCure on my nfdump files without all the nfsen headache?

**Comment by rickhofstede** [comment]
There's no supported means for analyzing historical data using SSHCure. More precisely, we implemented this in the past to be able to analyze (fixed) datasets for research purposes, but this requires a rather custom NfSen setup and is therefore unsupported.

**Comment by eljeffeg** [comment]
Ok, I'll keep at it with NFSEN and see where I get.  Does SSHCure rely on the port being 22?  My SSH activity is on a non-standard port.

**Comment by rickhofstede** [comment]
In its current form, SSHCure assumes _sshd_ to run on port 22, indeed. In theory, if you search and replace all references to this static/hardcoded port number, you should be good to go with _sshd_ running on other ports too.

**Comment by eljeffeg** [comment]
@rickhofstede I've modified the code to use the alternative port and from what I can tell from the interface and syslog, everything is working correctly.  However I haven't been able to get SSHCure to display anything when I put my data in the profile.  Trying to find out when the first successful login was during the brute force on port 2202 - it's a forensics challenge.  If you have any ideas, I'd be grateful for the tips.  

[nfcapd.201405230000.zip](https://github.com/SSHCure/SSHCure/files/2182081/nfcapd.201405230000.zip)

**Comment by rickhofstede** [comment]
What exactly do you mean by "putting data in the profile"? Do you mean live data or historic data? Based on the name/date of the attached file, you're feeding your profile with historic data.

In case you feed your profile with live data; if SSHCure does not present you with any detection results, it didn't detect any SSH scan or brute-force phase. For your reference, you can find the constants defined for and used by SSHCure [here](https://github.com/SSHCure/SSHCure/blob/master/backend/SSHCure/constants.pm). So what you should find in your data is this:

- Scan phase: single remote host and at least 25 hosts in your own network, scanned on port 2202.
- Brute-force phase: large number of flow records between a pair of hosts on port 2202 with a steady number of packets per flow, in the range of [11,51].

Hope that helps.

**Comment by eljeffeg** [comment]
It's historical data that I placed in the live directory as if it were recorded.  I thought that by maybe creating a new profile that covered the time period, it would initiate the sshcure process to run against the existing data.

Thanks for the constraints.  I'll see if I can figure it out along with reviewing the packets per flow.  The brute force attempt is obvious in the log - it's identifying the time of compromise(s) that I can't figure out. It's a challenging one for sure and sshcure seems to be the only tool that might be able to give me the answer.

**Comment by rickhofstede** [comment]
Your approach to integrate historic data in a live profile does not work; NfSen is not aware of any data placed manually in your profile. As such, the data will never be analyzed by SSHCure either.
